rucio/containers

server/rucio.conf.j2

CMS needs this setting to be settable.
Can you try to let me know when a container with it included is in docker hub? Right now I've had to switch to my own container.

Environment variable to allow encoded slashes

---

server/rucio.conf.j2

I found that certain clients (Go language) pass client certificate as a whole. This patch enforces apache server to follow the certificate chain. In order to validate client certificates though the proper SSLCACertificatePath and SSLCARevocationPath is required (I put standard /etc/grid-security/certificates).
Please note, that it is not required for curl or Python clients whose SSL library creates internally chain of certificates and pass them to apache server individually.

Enforce apache to follow chain of certificates

---

daemons/rucio.cfg.j2

Turns out these settings don't seem to be needed to get the TM running, but...

Add setttings for transmogrifier

---

daemons/rucio.cfg.j2

A couple of settings added recently to the conveyor for CMS's way of dealing with user transfers.

Add settings for user proxy work from Diego

---

probes/Dockerfile
probes/dot-jobber
probes/rucio.cfg.j2
probes/run-probes.sh

@tbeerman this container is now self contained (although should we consider a rucio-base container) and runs jobber to run the probes. 
I have this working in CMS with k8s. Next step is to do things with helm

Redo probes base on Jobber (cron replacement)

---

ui/Dockerfile

Need to get rid of the grid security volume here so we can install our own certs in the container. Otherwise we cannot get the UI to work with non-CERN certs.

Remove VOLUME from Dockerfile

---

daemons/Dockerfile
daemons/Dockerfile_py3
probes/Dockerfile
server/Dockerfile
server/Dockerfile_py3
ui/Dockerfile

By removing or never generation caches of rpm and pip installs, we can drastically reduce the size of the images. 
A test with daemons shows the added amount goes from 400 MB down to 210 MB for the install: https://hub.docker.com/repository/registry-1.docker.io/ericvaandering/test-daemons/tags?page=1
1.0.0 is the deftaul
1.0.1 removes RPM caches
1.0.2 eliminates pip caching

Reduce image bloat by about half

---

fts-cron/Dockerfile
fts-cron/docker-entrypoint.sh

Openshift seems to have more restrictive settings regarding setting root directory permissions compared to raw Kubernetes. Instead, do all the work of the fts-cron container in a "non-root" directory to work around this issue consistently for all cluster types.

Modify FTS3 Delegation CronJob to not require access to the root directory

---

probes/Dockerfile

The probes are not building because of this error fixed elsewhere. Can you merge this and trigger a build of the probes container? It still dates from an old install of Rucio

Fix the ordering of pip and setuptools to allow container to build

---

server/rucio.conf.j2

In case you need to move where the Apache logs are saved, I added an environment variable to do so.
In our case I want to write the logs to a shared persistent volume with the Rucio daemons, which can be seen by a pod running a Filebeat container.

Add environment variable to specify httpd logging directory.

---

ui/rucio.conf.j2

Need to also specify the logging directory for the Web UI for export to Fermilab persistent storage.

Add HTTPD logging directory environment variable to web UI

---

clients/Dockerfile
clients/Dockerfile_py3
clients/init_rucio.sh

I propose some changes to your pull request to make Singularity work as well. The issue with the previous setup was that /home gets automatically mounted in in Singularity, so anything that is put there will basically not be available inside a Singularity container.
I tested this works in Singularity. I have to admit I didn't fully test the functionality in Docker.

Support the container conversion to Singularity

---

server/docker-entrypoint.sh

This is necessary when running the server with `docker run --restart always` so that the server can start properly after a docker restart.

kill any running httpd processes before starting

---

clients/rucio.cfg.j2
daemons/rucio.cfg.j2
probes/rucio.cfg.j2
server/rucio.cfg.j2
ui/rucio.cfg.j2

If RUCIO_CFG_POLICY_PACKAGE is set, it is used to specify in rucio.cfg the policy package that is to be used.

Add policy package option to Rucio configuration file templates.

---

server/rucio.conf.j2
ui/rucio.conf.j2

Generate the WSGIScriptAlias for the main flask endpoint when it is selected.
Also add this option for the ui container.

Add flask option for RUCIO_SERVER_TYPE

---

dev/httpd.conf

since only 443 is used, which is defined in `rucio.conf`.
Port 80 clashes with graphite when running docker-compose configurations from the main repo in the same network namespace.

Remove listening on port 80 in dev container

---

fts-cron/dteam-voms.hellasgrid.gr

Second (first) VOMS server was [removed](https://operations-portal.egi.eu/vo/view/voname/dteam) more than a year ago.

Remove obsolete dteam VOMS server dteam-voms.hellasgrid.gr

---

fts-cron/renew_fts_proxy_dteam.sh.j2

fts-rest-delegate / fts-delegate-init don't delegate new proxy unless the old one expiration time is less than 6 hours. On the other hand FTS reject to submit transfer if delegated proxy expiration time is less than 1.5 hours. Both these constants are hardcoded directly in FTS sources.
It is necessary to delegate proxy at least every 4.5 hours otherwise there is a chance you'll not have proxy usable for job transfers or with fts-rest-delegate it is possible force FTS delegation with --force CLI option ... this second option is better, because with default delegation every 6 hours and lifetime 24 hours we can afford few attempts to fail and still have delegated proxy on FTS server with sufficient expiration time.

Force FTS proxy delegation for dteam VO

---

daemons/rucio.cfg.j2
server/rucio.cfg.j2

Add some newer setting which are needed for GlobusOnline transfers. Also include the use_preparer setting in the server since the server has to be aware of this.

Add use_preparer and other settings necessary for Globus Online

---

dev/Dockerfile

When a requirements.txt file exists, dependencies are installed from there. Following https://github.com/rucio/rucio/pull/4664 (rucio/rucio#4456).
Also add better handling and customization of git clone.

Add support for requirements.txt in dev containers

---

server/rucio.cfg.j2

The server needs the cert configuration to be able to update rule priority. The secret is now automatically updated after moving to new helm charts : https://github.com/rucio/helm-charts/pull/52 , but we need to update rucio.cfg to take the new secret into account.

Add usercert to config/conveyor

---

dev/Dockerfile

Enables integration tests with the [mariadb](https://pypi.org/project/mariadb/) package.

Add mariadb-connector-c to dev container

---

server/rucio.conf.j2

Since 1.26.0, there is only `flask` server type, so this logic is no longer necessary.

Remove RUCIO_SERVER_TYPE logic

---

.github/workflows/docker-auto-build.yml

close #146
Workflow is triggered when a "New Release" is created.
Currently, it auto builds and publishes to docker hub the images for clients, server and daemons.
Sample run for 1.26.2 release:
Trigger Event: https://github.com/maany/containers/releases/tag/1.26.2 
Workflow run: https://github.com/maany/containers/actions/runs/1190538947 
Published image (server, 1.26.2): https://hub.docker.com/r/maany/rucio-server/tags?page=1&ordering=last_updated
Published image (clients, 1.26.2): https://hub.docker.com/r/maany/rucio-clients/tags?page=1&ordering=last_updated
Published image (daemons, 1.26.2): https://hub.docker.com/r/maany/rucio-daemons/tags?page=1&ordering=last_updated

docker auto build and push - new workflow

---

daemons/rucio.cfg.j2
probes/rucio.cfg.j2

That leads to a lot of warning messages on the brokers. Instead rather point them to localhost by default.

remove atlas brokers from default config. Closes #3

---

clients/Dockerfile
init/Dockerfile
probes/Dockerfile
ui/Dockerfile

The `clients`, `ui`, `probes` and `init` Dockerfile's try to execute
`pip install --no-cache-dir --upgrade pip`
However, beyond `pip>21`, the new py3 syntax causes these upgrades and hence the auto-builds to fail.
To support py2 in these docker files, it is required to upgrade pip to`< 21` and optionally `setuptools < 45`
Example of the fixed CI run: https://github.com/maany/containers/actions/runs/1805773898

fix 1.23.x py2 build issues

---

fts-cron/renew_fts_proxy.sh.j2

Redhat 8 based systems need 2048 bit proxies. FTS has been upgraded to allow them to be delegated. This is working for CMS. Please merge.

Generated 2048 bit proxies for FTS

---

clients/Dockerfile
daemons/Dockerfile

Mihai confirmed that the new naming convention starting from `v1.10.0` is `pythonX-gfal2`.

Change GFAL2 python3 binding dependency to new naming convention

---

ssh/Dockerfile

The auto-builds failed as installation of the latest `dumb-init` package requires a GCC compiler, which was not available in the ssh container.

fix ssh_container

---

dev/Dockerfile

Upgrade `git` from version 1.8 to 2.36 by installing the package `git236` instead of `git`.
rucio/rucio#5765 needs `git >= 2.18` for the git worktree feature. It's also nice for developers to have a more up to date version, for instance the VSCode extension `GitLens` requires `git >= 2.7.2`.

rucio-dev: Upgrade git from version 1.8 to 2.36

---

fts/Dockerfile
fts/docker-entrypoint.sh
fts/fts3rest.conf
fts/fts3restconfig

This was a major fts release which migrated to using python3 and
had a major re-design of fts rest.
Some scripts are broken because of that. They were not migrated yet.

adapt installation and configuration for fts 3.12

---

dev/Dockerfile
server/docker-entrypoint.sh

- the lower-case version was deprecated by the upstream library, so switch
to upper-case
- chown was applied on the wrong line, so the env variable was
completely wrong

fix prometheus multiproc dir env variable

---

webui/.env.default.j2
webui/Dockerfile
webui/README.md
webui/docker-entrypoint.sh
webui/httpd.conf.j2
webui/robots.txt
webui/rucio.conf.j2

Add the `Dockerfile`, `docker-entrypoint` and configuration file templates for building a production container for the new React based webui.
The webui can operate with/without TLS Termination i.e. it can be served as a pure HTTP app, however, in that case x509 certificate verification is disabled.

Add containers and configuration for the new webui

---

fts-cron/Dockerfile_cpp
fts-cron/Dockerfile_java
fts-cron/docker-entrypoint.sh
fts-cron/renew_fts_proxy_multi_vo.sh.j2

Created a new multi-vo script, `renew_fts_proxy_multi_vo.sh.j2`, which allows the renew fts proxy cron job to renew several proxies at once for different VOs.
Made changes to the `Dockerfile` to add the new script to the container and added selection condition to `docker-entrypoint` to select the multi vo script.

Added Multi-Vo functionality to FTS cron job

---

dev/Dockerfile

Integration tests for 1.26 releases fail: https://github.com/rucio/rucio/actions/runs/3461834194/jobs/5779940105
```
==========================
Unsupported Python version
The integration tests for 1.26 releases fail with the following error
==========================
This version of Requests requires at least Python 3.7, but
you're trying to install it on Python 2.7. To resolve this,
consider upgrading to a supported Python version.
If you can't upgrade your Python version, you'll need to
pin to an older version of Requests (<2.28).
```
This commit pins the version of the requests package needed by the python2 dependencies (fts-rest-client)

pin requests version for py2 fts-rest-client in dev container

---

fts-cron/renew_fts_proxy_tutorial.sh.j2

FTS client was updated to 3.12, which uses a python client now, so CA certificates from grid-security aren't used automatically anymore.

add capath to tutorial fts_rest_delegate

---

xrootd/Dockerfile
xrootd/ca.repo

Add CERN CA installation to the Dockerfile of `xrootd` container for CERN certs to be trusted.

enhancement: install cern ca fix #223

---

.github/workflows/docker-auto-build.yml
daemons/alma9.Dockerfile
daemons/start-daemon.sh
server/alma9.Dockerfile
server/docker-entrypoint.sh
server/gacl
server/rucio.conf.j2

To both support python3.6 and python3.9 in docker-entrypoint.sh, the rucio python path is automatically inferred and passed as a variable to j2 scripts.

servers and daemons: build alma9 images

---

daemons/alma9.Dockerfile

Similarly to servers. Was forgotten. It's still used by some CAs.

daemons: allow sha1 on alma9

---

daemons/alma9.Dockerfile
daemons/openssl.spec
daemons/start-daemon.sh

Adapt the current dockerfile to always build openssl3.1 and davix and store the new RPMs ready for installation. This is to avoid having to build two different containers for alma9.
Add an ENV variable switch in the start-daemon.sh script to install these RPMs, if desired, just before running rucio.

servers: build openssl3.1 for alma9 daemons

---

.github/workflows/docker-auto-build.yml

Otherwise we end with double `-`.

build: remove '-' from alma9 custom tag. Closes #236

---

fts-cron/Dockerfile_java
fts-cron/docker-entrypoint.sh

For people who mount the final CRLs directly into the container.
If not explicitly disabled, default to the old behavior of
fetching the CRLs.

fts-cron: allow to disable fetch_crl

---

.github/workflows/docker-auto-build.yml

In the recent changes related to pushing versioned containers for everything, the `rucio-fs` naming scheme was changed to `fs`, which was not an intentional change. This commit fixes the error.

build: prepend-rucio to fs containers

---

daemons/alma9.Dockerfile
daemons/start-daemon.sh

Can still be disabled by setting the env variable
USE_DAVIX_WITH_OPENSSL31 to anything != 'True'

daemons: use openssl 3.1 by default

---

daemons/alma9.Dockerfile

it's already done in the centos7 containers
I just forgot about it in alma9.Dockerfile

daemons: install globus dependencies in alma9 daemons

---

dev/rucio.conf
server/rucio.conf.j2

Fix #216 
The changes in this PR work in conjunction with the changes documented in https://github.com/rucio/rucio/issues/6048 
This is required to trigger an x509 client certificate popup in the browser when the WebUI makes a request to the x509 endpoint.

server: explicitly request client certs for x509 endpoint #216

---

webui/README.md
webui/rucio.conf.j2

Removed SSL_CLIENT_VERIFY and RUCIO_CA_PATH config vars
Fix #219 
The following configuration has been moved to rucio server's `httpd.conf.j2` template. https://github.com/rucio/containers/issues/216
```
<Location /auth/x509> 
SSLVerifyClient optional_no_ca
SSLVerifyDepth 10
</Location>
```
and `post-handshake` authentication works as expected. So we can clean up the apache config for the new webui.
The entire scope of changes is described [here](https://github.com/rucio/rucio/issues/6048).

webui: cleanup SSL config #219

---

server/rucio.conf.j2

Sets `SSLVerifyClient require` on `/auth/x509/webui` endpoint
https://github.com/rucio/rucio/pull/6295 
https://github.com/rucio/rucio/issues/6294

server: add /auth/x509/webui endpoint

---

fts/Dockerfile
fts/fts3-token-test.repo

not 100% sure it's enough for tokens, but FTS starts and passes our other tests without issues.

fts: use the token test repository. Closes #266

---

server/rucio.conf.j2

This will make integration in kubernetes with proxy protocol enabled much easier. Do exactly the same thing as we do for the prometheus metrics endpoint a couple of lines above.

servers: allow exposing a separate health-check port

---

server/rucio.conf.j2

otherwise it complains about the require_x509_auth variable not being set.

servers: fix ping endpoint when ssl enabled

---

.github/workflows/docker-auto-build.yml

Otherwise, it will not generate correctly the -alma9 tag.

Only push alma9-latest tag if latest tag is also set

---

fts/Dockerfile

fts clients are not supported anymore.
zeromq is required by fts but not automatically installed

fix fts container build

---

webdav/Dockerfile
xrootd/Dockerfile

In preparation for the feature in rucio which introduces the torrent transfertool

xrootd & webdav: install the headless qbittorrent package

---

daemons/Dockerfile
daemons/start-daemon.sh
server/Dockerfile
server/docker-entrypoint.sh
webui/Dockerfile
webui/docker-entrypoint.sh

fixes #238 - explicitly failing container setup when patching fails
fixes #249  - filtering patches by directory in order to apply bin and lib patches separately

Patching: filter and apply bin and lib patches separately, and fail explicitly if patching fails (fix #238 and #249)

---

daemons/Dockerfile
daemons/start-daemon.sh
server/docker-entrypoint.sh
webui/docker-entrypoint.sh

Beforehand, `patchutils` was being installed as part of the `rpm_builder` image, resulting in `filterdiff` not being found in the final base image - fixing this in this PR
See https://stackoverflow.com/questions/33322103/multiple-froms-what-it-means for more information

Install `patchutils` as part of the later image in the Dockerfile

---

clients/Dockerfile
clients/README.md
clients/entrypoint.sh

This makes it possible to directly run a command in the docker image like this:
```
docker run [...] -v rucio-clients rucio download test:test.dat
```
`-l` is necessary to have bash load the startup script in `/etc/profile.d/` which sets up the rucio config.
Alternatively, that code could also be integrated into the entry point.

Change clients to have a login bash as entrypoint

---

ui/rucio.conf.j2

The error was spotted when I tried to install the rucio-ui helm charts with `.Values.service.useSSL = False`. The container failed to start as it was string to configure the SSL module.
This PR fixes the issue by only configuring the SSL module when the environment variable `RUCIO_ENABLE_SSL` has been explicitly set to true.

rucio-ui: use http is ssl is disabled.

---

xrootd/Dockerfile

xrootd: On alma9, use el9 repo instead of centos7

---

ui/Dockerfile
ui/README.md
ui/docker-entrypoint.sh
ui/rucio.conf.j2

The way the final `rucio.conf` was rendered from the Jinja template, lead to scenarios where configuration would not be correct and the UI homepage would look like
I have cleaned up and re-organized the template, so it renders coherently into a valid apache config

Rucio UI: Fix rendering issue, update Dockerfile and Apache config

---

daemons/start-daemon.sh
server/docker-entrypoint.sh

This is a prerequisite for https://github.com/rucio/rucio/issues/6632 and https://github.com/rucio/rucio/issues/6633.
The origin of the /etc/grid-security directory appears to be Globus. GFAL uses it transparently, but all other native system utilities and libraries do not.
This commits adds the Grid CAs to the system trust at the time the container starts, when applicable.  This will be important for the Rucio components that:
* Connect directly to the RSEs (Automatix, Dark Reaper, Reaper)
* Communicate with FTS (Cleaner, Poller, Submitter, and the Rucio servers)
The /etc/grid-security directory does not exist by default; it has to be populated externally and mounted in the container with extraHostPathMounts.

daemons/server: Add Grid CAs to the system trust

---

fs/Dockerfile
ssh/Dockerfile

- Created the symlink : `/usr/bin/python3` -> `/usr/bin/python`
- Removed installation of `centos-release-scl` and build tools that are already present in alma9
- switched to `dnf` over `yum`

Fix build of `ssh` and `fs` containers

---

dev/Dockerfile
ssh/Dockerfile

The outdated `rclone` versions (1.57-DEV) in the `dev` and `ssh` container do not work with the openssl versions available in those containers. This is causing the rclone integration tests to fail https://github.com/rucio/rucio/issues/6763 
This PR bumps the `rclone` version to the latest available version. I recreated the failing integration tests, applied this patch which made the tests pass.
p.s. this will require a release ( or at least pushing the updated containers to Docker Hub), so that the integration tests can use the updated containers

dev, ssh: update rclone to latest

---

fts-cron/vomses/vo.compass.cern.ch-voms-compass-auth.cern.ch

COMPASS is a CERN experiment that will use RUCIO, as such, the COMPASS VO needs to be configured, therefore this PR.

FTS-CRON: add COMPASS voms information

---

fts/Dockerfile

3.14.0-r2404100902git47e773b is the latest FTS version that was used in Rucio 34.2.0, which was released on 2024-04-16.
This change is to address this issue:
https://github.com/rucio/rucio/issues/6774.
The `fts-libs` is added as direct dependency (specifically, `fts-libs-3.14.0-r2404100902git47e773b.el7.cern.x86_64`) because it is required by `fts-server-3.14.0-r2404100902git47e773b.el7.cern.x86_64`, and for some reason the dependency resolution errors out if it tries to find the correct `fts-libs` version when it's not specified.
fts-monitoring has no specified versions in the fts3-token-test repo, so it's left unpinned to latest. (I'm not even sure if this package actually gets installed, as there's this log in the Docker build logs: No package fts-monitoring available.")

FTS: Pin FTS to latest version used in Rucio 34.2.0

---

ssh/sshd_config

This was deprecated in OpenSSH 7.5: https://www.openssh.com/txt/release-7.5
>  * This release deprecates the sshd_config UsePrivilegeSeparation option, thereby making privilege separation mandatory. Privilege separation has been on by default for almost 15 years and sandboxing has been on by default for almost the last five.

SSH: Remove deprecated UsePrivilegeSeparation option; #311

---

dev/Dockerfile

As part of https://github.com/rucio/rucio/issues/6750, we split `requirements.txt` in `rucio/rucio` into separate requirements files, depending on the application. We are keeping this change unreleased until the next major Rucio release.
Until then, integration tests on `rucio/rucio:master` will use the new `requirements.dev.txt` file, while the ones on `rucio/rucio:release-34` will use the old `requirements.txt` file.
This commit is a temporary fix which will be removed after the next major release. This issue will remain open until then: https://github.com/rucio/containers/issues/323

Dependencies: Temporarily accept either requirements.txt and requirements.dev.txt in the dev container

---

ui/README.md
ui/rucio.conf.j2

In deployment scenarios where the Rucio UI sits behind a proxy ( a loadbalancer or another reverse proxy), the client information must be handled by the UI container's httpd process.
This PR configures the `RemoteIPProxyProtocol` directive to enable the UI do to so

ui: add option to configure `RemoteIPProxyProtocol` directive

---

ui/README.md
ui/rucio.conf.j2

This variable can be used to add an additional `Redirect` in the apache config. The value should be a string with the format `/{path} {url}`.
For example `RUCIO_HTTPD_ADDITIONAL_REDIRECTS="/foo http://bar"` will add the following lines to the apache config located at `/etc/httpd/conf.d/rucio.conf` inside the container:
```bash
Redirect /foo http://bar
```
You can add multiple refirects if you specify the value of the environment variable in the following format: `/{path1} {url1}, /{path2} {url2}, ...`. For example `RUCIO_HTTPD_ADDITIONAL_REDIRECTS="/foo http://bar, /baz http://qux"` will add the following lines to the apache config located at `/etc/httpd/conf.d/rucio.conf` inside the container:
```bash
Redirect /foo http://bar
Redirect /baz http://qux
```

ui: add `RUCIO_HTTPD_ADDITIONAL_REDIRECTS` environment variable

---

ui/Dockerfile
webui/Dockerfile

#331 introduced patching the UI containers, however patching fails because of missing packages:
```
Applying patch /patch/ui-dumps-banner.patch
/docker-entrypoint.sh: line 48: filterdiff: command not found
Error while filtering patch /patch/ui-dumps-banner.patch/bin. Exiting setup.
```
This PR is a follow-up to install the missing packages required for patching

ui, webui: install patch, patchutils

---

dev/rucio.cfg

Fix x509 identity to new schema

---

fts-cron/Dockerfile_cpp
fts-cron/Dockerfile_java
fts-cron/docker-entrypoint.sh
fts-cron/wlcg-el9.repo

I had to remove the `lcg-CA` package. I am not sure what it used to do and what is the alma9 alternative. 
In any case, once these changes are released, we should check if the proxy gets issued correctly on the kubernetes side. 
----
I ran the `Dockerfile_java` in the kubernetes cluster and was successfully able to generate the proxy and also the kubernetes secret

fts-cron: migrate to alma9 #340

---

ssh/Dockerfile

Fixing an error when building the `ssh` container:
```
#12 [7/8] RUN mkdir /rucio /root/.ssh &&     echo '' > /root/.ssh/authorized_keys
#12 0.053 mkdir: cannot create directory '/root/.ssh': File exists
#12 ERROR: process "/bin/sh -c mkdir /rucio /root/.ssh &&     echo '' > /root/.ssh/authorized_keys" did not complete successfully: exit code: 1
```

SSH: add -p flag when running mkdir

---

fs/Dockerfile

In the fs/Dockerfile the installation of the g++ compiler is missing, thus the building stage of the rucio-fs fails.
This fix just add the installation of the compiler.

added installation of g++ inside the rucio-fs container

---

server/rucio.conf.j2

Fix #352 
At /auth/x509/webui, client certificate verification is made optional on OPTIONS requests. This will ensure proper authentication across all browsers in the new version of the UI.

Patch apache config to exclude OPTIONS requests from client certificate checks

---

server/rucio.conf.j2

The source code of webui has been changed to include client credentials in requests sent to this endpoint.

server: make SSLVerifyClient optional for /auth/x509/webui

---

.github/workflows/docker-auto-build.yml
daemons/Dockerfile
server/Dockerfile
test-xrootd/Dockerfile

- de7b51e7d0828dbd839f45b2cadde340e4bfdb0f fixes https://github.com/rucio/containers/issues/365
- the other commits address https://github.com/rucio/containers/issues/354
The only two unsupported images are currently:
- `test-fts` - FTS doesn't provide an arm-based image
- `probes`: pending https://github.com/rucio/containers/issues/369
Related: https://github.com/rucio/rucio/issues/7162 - we would need to change this PR to only set `amd64` for `test-fts` and `probes`.

Add arm64 as build target for supported images

---

clients/Dockerfile
daemons/Dockerfile
init/Dockerfile
server/Dockerfile
ui/Dockerfile

Fixes #364
I haven't modified the container READMEs for now. I plan to mostly include info on policy package deployments in the main policy package docs, under this other issue https://github.com/rucio/documentation/issues/456
Example usage:
```
docker build --no-cache -t test-server --build-arg POLICY_PACKAGE_REQUIREMENTS=atlas_rucio_policy_package==0.4.0,git+https://github.com/rucio/temporary-belle2-policy-package@v0.1.0 --build-arg TAG=36.2.0 .
```
Verifying installation (this is after importing the modules):
```
>>> rucio
<module 'rucio' from '/usr/local/lib/python3.9/site-packages/rucio/__init__.py'>
>>> atlas_rucio_policy_package
<module 'atlas_rucio_policy_package' from '/usr/local/lib/python3.9/site-packages/atlas_rucio_policy_package/__init__.py'>
>>> belleii_rucio_policy_package …
```

server,clients,daemons,ui,init: add policy package build arg support

---

dev/Dockerfile

Replace gfal2-python3 alias with the real package name python3-gfal2.

Replace gfal2-python3 alias Fix #380

---

.github/workflows/docker-auto-build.yml
dev/Dockerfile

Pin rucio-dev image using ARG TAG, with early failing if no tag is provided.
Also, previously, the workflow used `github.repository_owner` when constructing Docker image tags, which caused push failures if the GitHub username did not match the Docker Hub username. This commit switches to using the `DOCKER_HUB_USERNAME` secret for the base tag. This should not affect actually any official build process where both usernames are identical (hence, the Docker Hub namespace should remain correct). The change is mostly for dev support.

Pin dev image version Fix #379

---

dev/Dockerfile

Should fix the end-to-end tests
```
#7 [ 2/31] RUN test -n "$TAG" || (echo "No TAG specified. Exiting." && exit 1)
#7 0.208 No TAG specified. Exiting.
```
this should be fixed by merging https://github.com/rucio/rucio/pull/7500 anyway, but I think it's a good idea to set the master branch as default

dev: set master branch to default arg for pulling

---

server/rucio.conf.j2

Same default behaviour as before, this change preserves backwards compatibility.
Relted to https://github.com/rucio/containers/issues/392

Add support for `AllowEncodedSlashes NoDecode` via new env variable

---

dev/alembic.ini
dev/rucio.cfg
dev/rucio_multi_vo_ts2.cfg
dev/rucio_multi_vo_tst.cfg

This pull request includes several changes to update the database connection URL to use `psycopg` instead of the default PostgreSQL adapter. These changes are made across multiple configuration files to ensure consistency.
This was the root cause behind the dev containers not starting up as they were using the incorrect driver to connect to the database.
Database connection URL updates:
* [`dev/alembic.ini`](diffhunk://#diff-1e7a48965b7b7d1ce5f811c504381194b579f2f7bb31f6be108e434138adaf51L28-R28): Updated the `sqlalchemy.url` to use `postgresql+psycopg` instead of `postgresql`.
* [`dev/rucio.cfg`](diffhunk://#diff-9f7058724fb0d51f1d2b36a4ed4e0c30c79872dc12fd2c7470f363b9a234a04aL20-R20): Updated the `default` database URL to use `postgresql+psycopg` instead of `postgresql`.
* …

dev: Update database connection string to use postgresql+psycopg

---

fts-cron/renew_fts_proxy_multi_vo.sh.j2

The config required is now only the list of VOs and VOMS roles defined in the fts-cron section
The script will then generate proxy to the number of defined VOs, delegate to FTS for each, and collect into a single secret that is then defined in the daemons config for conveyor as prepared by Radu

Update multi-vo fts renew script; Fix #177
