rucio/containers

daemons/rucio.cfg.j2, server/rucio.cfg.j2
We need to be able to set this for CMS. Should be completely transparent.
=> Add ability to set lfn2pfn_module

daemons/rucio.cfg.j2
=> Fix hermes e-mail address

server/Dockerfile
Placeholder, don't merge just yet
=> Remove VOLUME for /etc/grid/security to allow VOs to populate it

server/rucio.conf.j2
Follow up pull request for issue #14
=> Disable TRACE and TRACK methods fixes #14

probes/Dockerfile, probes/run-probes.sh
I don't know where, if anywhere, this would have to be added to the build and upload to docker hub procedure.
=> Add a container in which probes can be run.

daemons/rucio.cfg.j2
the probes container is based off the daemons container, so add a little bit to the config files for daemons
=> Add nagios section for probes

server/rucio.cfg.j2
A couple of minor problems we fixed when getting the trace server up and running in k8s
=> Fix trace server

daemons/rucio.cfg.j2
=> All kronos stuff should start with tracer_kronos, not just tracer

ui/Dockerfile
=> Explicitly install Rucio first

dev/Dockerfile
Dev Dockerfile now creates the directories for the mVO config files, and copies them to these new locations in line with changes to the main codebase.
=> Update Dockerfile with mVO cfg locations, #90

probes/rucio.cfg.j2
First PR of what I was describing in Slack
=> Add prometheus settings to probes config

clients/Dockerfile, clients/Dockerfile_py3, clients/init_rucio.sh, clients/j2cfg.py, clients/rucio.cfg.j2, daemons/Dockerfile, daemons/Dockerfile_py3, daemons/j2cfg.py, daemons/rucio.cfg.j2, daemons/start-daemon.sh, daemons/start-daemon_py3.sh, server/Dockerfile, server/Dockerfile_py3, server/docker-entrypoint.sh, server/j2cfg.py, server/rucio.cfg.j2
=> Revert "add default email config option + some rucio.cfg formatting changes"

dev/rucio.cfg
Adds all Flask endpoints necessary for testing.
=> Add endpoints configuration to dev container

fts/Dockerfile, fts/docker-entrypoint.sh
=> Update FTS version

daemons/rucio.cfg.j2
these are both required to use elastic/influx with hermes2
=> added [hermes.elastic_endpoint] and [hermes.influxdb_endpoint] cfg items

dev/Dockerfile
=> setup minimum requirements for fts_rest_cli #128

dev/rucio.conf
Fixes WebUI in dev container. Best merged after https://github.com/rucio/rucio/pull/4564
=> Fix order of aliases

dev/rucio.cfg, fts/Dockerfile, fts/docker-entrypoint.sh, fts/fts-msg-monitoring.conf
Will be used for testing the receiver in rucio integration test suite.
=> Configure ActiveMQ in fts and rucio/receiver

server/rucio.conf.j2
=> Revert "Remove RUCIO_SERVER_TYPE logic"

server/rucio.conf.j2
Reverts rucio/containers#149
After all, this change was completely fine 😏
=> Revert "Revert "Remove RUCIO_SERVER_TYPE logic""

.github/workflows/docker-auto-build.yml
=> auto build/push all containers for every release in release-1.20-LTS

clients/Dockerfile
Fixing #169 (see there for discussion)
=> Adding argcomplete to client pip

server/rucio.conf.j2
avoid multiple levels of if/else which are difficult to follow
=> simplify servers rucio httpd template

server/rucio.conf.j2, ui/rucio.conf.j2
=> Modify the server default TLS versions

dev/rse_repository.json
required for the integration tests in https://github.com/rucio/rucio/pull/5524
=> update rse ssh_disk to ssh-disk

fts/Dockerfile
=> add a software collections repo for fts #198

ui/rucio.conf.j2
Similar to https://github.com/rucio/containers/pull/193 it shouldn't be surprising that WebUI needs to be modified too.
=> Add Legacy DN format support to WebUI

fts/Dockerfile
FTS 3.12 uses python3 and installs dependencies from their dedicated repository
=> fix fts container creation

fts-cron/docker-entrypoint.sh
This change builds on top of https://github.com/rucio/helm-charts/pull/139 while being compatible with old helm chart versions.
=> fts-cron: prefer "script" variable over "vo" to pick the script

dev/Dockerfile
was forgotten when removing the keys
=> don't chmod non-existing ssh keys

probes/Dockerfile
=> Remove fixed version of cx-oracle

server/docker-entrypoint.sh, webui/.env.default.j2, webui/Dockerfile, webui/docker-entrypoint.sh
=> webui: prepare containers with NextJS

server/docker-entrypoint.sh
=> Fix docker entry point in server/docker-entrypoint.sh

clients/Dockerfile, clients/README.md, clients/init_rucio.sh, clients/rucio.default.cfg
The jinja file was fallbacking to a default config, so this was a regression to completely remove it.
=> add a default rucio config in clients. #267

fts/Dockerfile
=> fts: use the release candidate repository

dev/rucio.conf
=> dev: configure tls 1.2 in apache config

dev/Dockerfile
Part of https://github.com/rucio/rucio/pull/6767
=> Testing: Modify filename of requirements file

ui/docker-entrypoint.sh
=> ui: add patches and CA trust anchors #331

dev/Dockerfile
=> Dev: remove temporary workaround for old requirements format

daemons/Dockerfile, daemons/start-daemon.sh
See https://github.com/rucio/containers/issues/365#issuecomment-2734459680
Thanks Radu for spotting this!
=> daemons: Remove USE_DAVIX_WITH_OPENSSL31 usage; #365

webui/README.md
I copied the table from the webui repo in order for both to be identical, that is why such a big diff
=> Add `LIST_DIDS_INITIAL_PATTERN` to readme

.github/workflows/shell-check.yml, dev/create_monit_data, webui/docker-entrypoint.sh
As per the issue #410 added a new workflow to handle this thing using an action https://github.com/marketplace/actions/shellcheck
=> #410 Consider implementing Shellcheck in the CI

dev/Dockerfile
=> Remove old *pip-requires* leftovers"; Fix #422
